// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUvaKtMjReYCLR4ecHOWUASD-m_Th8_eQ',
    appId: '1:852393992397:web:c089fc9dddd60bf2848984',
    messagingSenderId: '852393992397',
    projectId: 'ecosight-704c9',
    authDomain: 'ecosight-704c9.firebaseapp.com',
    storageBucket: 'ecosight-704c9.firebasestorage.app',
    measurementId: 'G-8Q5DVHW1FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKIGFkVTAwefz_oQBJuIi3bN9lHnnJxPw',
    appId: '1:852393992397:android:f25bd3e9003d11cc848984',
    messagingSenderId: '852393992397',
    projectId: 'ecosight-704c9',
    storageBucket: 'ecosight-704c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgzK5WFPxvm5_EYbUGyU78MxaeGIJAufA',
    appId: '1:852393992397:ios:0bcb51f7f5cace24848984',
    messagingSenderId: '852393992397',
    projectId: 'ecosight-704c9',
    storageBucket: 'ecosight-704c9.firebasestorage.app',
    iosBundleId: 'com.example.ecosightApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgzK5WFPxvm5_EYbUGyU78MxaeGIJAufA',
    appId: '1:852393992397:ios:0bcb51f7f5cace24848984',
    messagingSenderId: '852393992397',
    projectId: 'ecosight-704c9',
    storageBucket: 'ecosight-704c9.firebasestorage.app',
    iosBundleId: 'com.example.ecosightApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUvaKtMjReYCLR4ecHOWUASD-m_Th8_eQ',
    appId: '1:852393992397:web:3b6d56c235e49514848984',
    messagingSenderId: '852393992397',
    projectId: 'ecosight-704c9',
    authDomain: 'ecosight-704c9.firebaseapp.com',
    storageBucket: 'ecosight-704c9.firebasestorage.app',
    measurementId: 'G-N0TMNEN9WL',
  );
}
